config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.connect "/paper_downloads/test", :controller => 'paper_downloads', :action => 'test'
  map.resources :paper_downloads

  map.resources :wom_requests

  map.devise_for :users
  map.resources :users, :member => [:login_as] do |users|
    users.resources :limitations, :shallow => true
  end
  map.resources :limitations

  map.resources :product_groups, :collection=> {
    :create_my_product => :post,
    :create_from_product_report => :post,
    :new_from_product_report => :get,
    :my_products => :get
  }, :member => {
    :aggregates_set => :post,
    :aggregates_get=> :get,
    :api_produce_mia_report => :get,
    :produce_cia_report => :post,
    :produce_cia_report_settings => :get,
    :produce_trending_products_report => :post,
    :produce_trending_products_report_settings => :get,
    :keywords => :get, :keywords_proxy => :get} do |product_groups|
      product_groups.resources :products, :only => :index, 
        :collection => {:index => :post},
        :member => {:add_to_group => :post, :remove_from_group => :post}
    end

  map.resources :product_reports, :member=>{:filter => :post, :refresh => :post, :mail => :post} do |reports|
    reports.resources :products, :shallow => true
  end

  map.resources :nps_reports, :member=>{:filter => :post, :refresh => :post, :mail => :post} do |reports|
    reports.resources :products, :shallow => true
  end

  map.psa_report_completion '/psa-report-complete/user/:user_id/product/:product_id', :action => 'psa_report_completion', :controller => 'product_reports'

  map.resources :reviews, :manufacturers, :products

  map.resources :categories, :member=>{:subscribe => :post, :unsubscribe => :post}, :collection => {:search => :get} do |categories|
    categories.resources :products, :shallow => true, :only => :index
  end

  map.resources(:products,
                :member=>{
                  :report_settings_set => :post,
                  :report_settings_get => :get,
                  :trending_report_keywords => :get,
                  :psa_report_keywords => :get,
                  :produce_psa_report => :post,
                  :api_produce_psa_report => :get,
                  :produce_psa_report_settings => :get,
                  :produce_trending_report => :post,
                  :produce_trending_report_settings => :get})  do |products|
    products.resources :reviews, :shallow => true
  end

  map.resources :user_messages, :only => [:new, :create]
  map.contact_us_old 'ContactUs', :controller=>'user_messages', :action=>'new'
  map.contact_us 'Contact-Us', :controller=>'user_messages', :action=>'new'
  map.wom_request 'Wom-Request', :controller=>'wom_requests', :action=>'new'
  map.with_options :controller => "pages" do |page|
    page.root :action=>'home'
    page.jroot '/Home', :action=>'home'
    page.jroot_two '/home', :action=>'home'
    page.terms_of_service '/TermsOfService', :action=>'terms_of_service'
    page.registration_finished '/registered', :action=>'registration_finished'
    page.products_v2p_accelerator_old '/Products/V2P-Accelerator', :action=>'products_v2p_accelerator'
    page.products_v2p_accelerator 'V2P-Product-Reviews', :action=>'products_v2p_accelerator'
    page.products_wom 'Word-of-Mouth-Analysis', :action=>'wom'
    page.products_tour '/Products/Tour', :action=>'products_tour'

    page.products_methodology_old '/Products/Methodology', :action=>'products_methodology'
    page.products_methodology 'Consumer-Reports-Analysis', :action=>'products_methodology'
    page.products_prm_old '/Products/MarketIntelligenceReporter', :action=>'products_prm'
    page.products_prm 'Market-Research', :action=>'products_prm'

    page.prm_welcome '/prm_welcome', :action => 'prm_welcome'
#    page.services_old '/services', :action => 'services'
    page.services 'Consumer-Reports-Analysis-Services', :action => 'services'

    page.subscription_plans '/plans', :controller=>'pages', :action=>'plans'
  end
  
  
  map.with_options :controller => "methodology" do |page|
    page.root :action=>'index'
    page.methodology '/Methodology', :action=>'index'
    page.jroot_two '/methodology', :action=>'index'
  end
  
  map.v2p_accelerator_demo_old '/Products/V2P-Accelerator/Demo', :controller=>'v2p_accelerator', :action=>'demo'
  map.v2p_accelerator_product_submit 'V2P-Product-Reviews/Product-Submit', :controller=>'v2p_accelerator', :action=>'product_submit'
  map.v2p_accelerator_demo 'V2P-Product-Reviews/Demo', :controller=>'v2p_accelerator', :action=>'demo'
  map.v2p_accelerator_video 'V2P-Product-Reviews/Video', :controller=>'v2p_accelerator', :action=>'video'
  map.resources :v2p_accelerator, :only => [], :collection => {:compare_with_other_products => :post} 

  map.external_auth '/aai/seam/resource/services-v1/auth/details/:token', :controller=>'auth', :action=>'verify_token'

  map.connect '/v2p_accelerator/auto_complete_for_product_name', :controller => 'products', :action => 'auto_complete_for_product_name'

  map.connect '/MyAccount', :controller => 'registrations', :action => 'edit'
  
  map.connect "/get_captcha", :controller => 'newreports', :action => 'captcha'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/category.rb
class Category < ActiveRecord::Base
  self.table_name = "category"
  has_many :product_categories, :dependent => :destroy
  has_many :products, :through => :product_categories
  has_many :product_reports, :as => :category
  has_many :sent_reports, :as => :category
  acts_as_tree :order => "name"
 
  def manufacturers
    q = "SELECT `manufacturer`.* FROM `manufacturer`  INNER JOIN `product` ON `manufacturer`.id = `product`.manufacturer INNER JOIN `product_category` ON `product`.id = `product_category`.product_id   WHERE ((`product_category`.category_id = #{id}))  GROUP BY `manufacturer` ORDER BY `manufacturer`.name"
    Manufacturer.find_by_sql q
  end     

  def anchestors
    Category.where(id: self.parent_id)
  end
 
  def is_root?
    parent_id.blank?
  end
  
  def to_s
    name
  end
  
  def most_recent_updated_product
    @most_recent_updated_product ||= products.order('last_update DESC').first
  end
  
  def number_of_product_reviews
    products.sum('all_reviews_count')
  end
  
  def children_with_products
    #children.find  :all, :joins => :product_categories, :select => "category.*, count(product_id) as products_count", :group => "category.id", :having => 'products_count > 35'
    children.where("products_count >= #{APP_CONFIG[:min_number_of_categories]}")
  end
   
  def children_with_children
    children.find  :all, :joins => :children, :select => "category.*, count(childrens_category.id) as child_count", :group => "category.id", :having => 'child_count > 0'
  end
  
  def children_with_children_and_products
    Category.find :all, :conditions => "attrib_left > #{attrib_left} AND attrib_right < #{attrib_right} AND products_count >= #{APP_CONFIG[:min_number_of_categories]}"
  end
  
  def children_having_children_and_products
    #children.delete_if{|cat|
    #  !cat.has_children_with_children_and_products?
    #}
    children
  end
  
  def has_children_with_children_and_products?
    Category.count(:conditions => "attrib_left > #{attrib_left} AND attrib_right < #{attrib_right} AND products_count >= #{APP_CONFIG[:min_number_of_categories]}") > 0
  end
  
  def all_sub_children_with_products
    ch = all_sub_children
    ch.delete_if {|x| x.products_count < APP_CONFIG[:min_number_of_categories] }
  end
  
  def dom_id
    "category-#{id}"
  end
  
  def self.dom_id(id)
    "category-#{id}"
  end
  
  def update_node_attributes(attrib=1)
    update_attribute('attrib_left', attrib)
    attrib += 1
    children.each{|a|
      attrib = a.update_node_attributes(attrib)
    }
    update_attribute('attrib_right', attrib)
    attrib += 1
  end
  
  def self.find_by_manufacturer(man)
    find :all, :conditions => ["products_count >= #{APP_CONFIG[:min_number_of_categories]} AND id IN (SELECT DISTINCT product_category.category_id from product, product_category WHERE product.manufacturer = ? AND product.id = product_category.product_id)", man.id]
  end
  
  def self.find_by_product(product)
    find :all, :conditions => ["products_count >= #{APP_CONFIG[:min_number_of_categories]} AND id IN (SELECT DISTINCT product_category.category_id from product, product_category WHERE product.name = ? AND product.id = product_category.product_id)", product.name]
  end


end

app/models/product.rb
#require 'acts_as_ferret'

class Product < ActiveRecord::Base
  self.table_name = "product"
  has_many :product_category
  has_many :categories, :through => :product_category
  has_many :reviews
  
  belongs_to :manufacturer, :class_name => 'Manufacturer',:foreign_key => 'manufacturer'

  has_one :recent_review, :class_name => "Review", :order => "recieve_date DESC"

  attr_accessor :custom_csv_data

  #acts_as_ferret :fields => [ :name ]

  #comma do

  #  name
  #  manufacturer_name_from_preloaded_list 'Manufacturer'
  #  csi_score
  #  functionality_score
  #  reliability_score
  #  support_score
  #  number_of_reviews

  #end

  #comma :nps do
  #  name
  #  manufacturer_name_from_preloaded_list 'Manufacturer'
  #  nps_score
  #  last_update
  #  number_of_reviews
  #end

  def number_of_reviews
    @number_of_reviews ||= reviews_count
  end

  def to_s
    name
  end


  #this is emulation of ferret using native mysql 
  #nk, 2014
  def self.find_with_ferret term, opts = {}
    #using native mysql search in dev env
    return [] if term.blank?
    term.gsub!('"',"")
    term.gsub!("*","")
    words = term.to_s.downcase.split(" ")
    condition_template = ""
    condition_values = []
    order = ""
    words.each do |word|
      condition_template += " OR " if !condition_template.blank?
      condition_template += "(LOWER(name) like ?)"
      condition_values << "%#{word}%"
      order += " + " if !order.blank?
      order += "(LOWER(name) like ?)"
    end
    order = ActiveRecord::Base.send(:sanitize_sql_array,[order]+condition_values)
    opts = opts.merge( {:order=>"(#{order}) desc",:conditions=>[condition_template]+condition_values})
    paginate = {}
    if opts.has_key? :page
      paginate[:page] = opts[:page] 
      opts.delete :page
    end

    if opts.has_key? :per_page
      paginate[:per_page] = opts[:per_page]
      opts.delete :per_page
    end
    
    #ret = self.find(:all, opts)
    ret = self.where(opts[:conditions]).order(opts[:order])
    if !paginate.blank?
      ret.paginate(paginate)
    else
      ret
    end
  end

  def manufacturer_name_from_preloaded_list
    custom_csv_data[:manufacturers][attributes['manufacturer']]
  end

  def reviews_count
    all_reviews_count
  end

  def reliability_reviews(options = {})
    reviews.all({:conditions => "reliability_score != 1"}.merge(options))
  end

  def functionality_reviews(options = {})
    reviews.all({:conditions => "functionality_score != 1"}.merge(options))
  end

  def support_reviews(options = {})
    reviews.all({:conditions => "support_score != 1"}.merge(options))
  end

  def self.product_category_search(name, type, user, page = 1)
    categories = []
    #{"manufacturer"=>"LG", "product"=>"Portable Stereo Speakers", "categories"=>[{"fullPath"=>"Portable Audio & Video > MP3 Players & Accessories > MP3 Player Accessories > Speaker Systems", "id"=>330, "subscribed"=>false}]}
    products = Product.find_with_ferret("#{name}*", :page => page.blank? ? 1 : page)
    products.each{|p|
      #categories << {'product' => p.name, :categories => [{"fullPath"=>"Portab"}]}
      categories <<  {"manufacturer"=>p.manufacturer.try(:name), "product"=>p.name, "categories"=>[{"fullPath"=>p.categories.first.name, "id"=>p.categories.first.id, "subscribed"=>user.subscribed?(p.categories.first)}]}
    }
    p categories
    categories.paginate(:page => products.current_page, :per_page => products.per_page, :total_entries => products.total_entries)
  end

  # returns products added to My Lists of users
  def self.active_products
    Product.find_by_sql("SELECT id,  all_reviews_count FROM product WHERE id IN (SELECT DISTINCT(product_id) FROM  product_groupings) LIMIT 5000")
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def name_with_ancestors(category)
    s = ""
    if category
      ancestors = category.ancestors.reverse
      if ancestors.length > 0
        ancestors.shift 
        ancestors.each{|cat|
          s += "#{link_to cat.name, cat} &gt; "
        }
      end
      s += category.name
    end
    s
  end
end

app/views/products/_group_products.html.erb
<%= stylesheet_link_tag '/css/additional.css' %>

<% if @product_group.blank? || @product_group.try(:products).try(:empty?) -%>
  <br />
  <p>The list is empty.</p>
<% else -%>

<div class="table_body" style="border:none;">
  <table class="prm_table" cellspacing="0" style="width:737px;margin: 5px 3px 0 0px;">
    <tr>
      <th id="prod_name">Products (<%= @product_group.try(:products).try(:size) %>)</th>
    </tr>
    <% @product_group.products.each do |product| -%>
    <tr class="subscribed_categories">
      <td><%= link_to product["name"], product_path(product['id']), :class=>'blue' -%>
      <%= link_to_remote "Remove", :url  => {:controller => 'products', :action => "remove_from_group", :id => product.id}, :loading => "Element.show('loading_bar')", :with => "'product=#{params[:product]}&type=#{params[:type]}&page=#{params[:page]}'", :complete => "Element.hide('loading_bar')", :html => {:class=>"unsubscribe"} %></td>
    </tr>
    <% end -%>
  </table>
  <div style="margin-top: 11px" >
    <%= form_tag( produce_cia_report_product_group_path(@product_group), :id => 'pr_form' ) -%>
    <%= hidden_field_tag 'threshold', '75' %>
    <%= submit_tag 'Produce MIA report', :class => 'blue button_yellow cia_report_btn', :style => 'float:left; margin-left: 5px; margin-top: 1px;cursor:pointer;' -%>
    </form>
    <%= link_to 'Customize MIA report', produce_cia_report_settings_product_group_path(@product_group), :class => 'blue button_yellow', :style => 'float:left; margin-left: 5px; margin-top: 1px;' -%>
    <%= link_to 'NPS&reg; Monitor', new_nps_report_path(:selected_category => "#{@product_group.id}_group",:auto=>1),:class => 'blue button_yellow', :style => 'float:right; margin-left: 5px; margin-top: 1px;' -%>
  </div>
</div>
<div class="clearer"></div>
<% end -%>

<%= javascript_include_tag 'jquery-1.4.1.min' %>
<script>
  jQuery.noConflict();
  var time = new Date().getTime();
  jQuery(".cia_report_btn").attr("href",jQuery(".cia_report_btn").attr("href")+"&time="+time);
  jQuery(".mir_report_btn").attr("href",jQuery(".mir_report_btn").attr("href")+"&time="+time);
</script>

app/views/products/_product_lookup.html.erb
<div class='product_lookup'>
  <% if @same_url_query %>
    <%= form_tag("", :method => :get) %>
  <% else %>
    <%= form_tag(product_group_products_path(@product_group), :method => :get) %>
  <% end %>

    <table width="100%" style='height:60px;' >
      <tr>
        <td width="70%" rowspan=2>
          <%= text_field_tag :name, params["product"].blank? ? "" : params["product"] , :tabindex=>"0", :class=>"longEditbox", :name => 'product', :id=>'product' %>
        </td>
        <td width="10%" class="product_lookup_selector">
        </td>
        <td width="20%" align="right" style="padding-right: 15px" rowspan=2>
          <%= image_submit_tag "/aai/images/search-button.png" %>
        </td>
      </tr>
      <tr>
        <td width="10%" class="product_lookup_selector">
        </td>
      </tr>
    </table>

  </form>
</div>

app/views/products/_results.html.erb
<% form_remote_tag :url => refresh_product_report_path(@report), :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')", :html => {:id => "update_product_report_form"} do %>
  <div class="accordion_section">
    <div class="accordion_bar">
      <img src="/images/acc_head_left2.png" alt="" />
      <img src="/images/acc_resultsheader.png" alt="" />
      <img src="/images/acc_head_right.png" style="float: right;" alt=""  />
      <% if @products.next_page -%>
        <%= image_submit_tag("/images/nxt_button.png", :class=>"header_btns", :onClick => "$('update_product_report_form').form_action.value='next_page'") %>
      <% end -%>
      <% if @products.previous_page -%>
        <%= image_submit_tag("/images/prv_button.png", :class=>"header_btns", :onClick => "$('update_product_report_form').form_action.value='prev_page'") %>
      <% end -%>
      <%= per_page_select(@report.items_per_page) %>
      <label class="rowdd"><%= page_entries_info(@products) %></label>

      <% if @report.filtered? -%>
        <%= image_submit_tag("/images/clrfilter.png", :style=>"float:right;", :name=> "clear_filter", :value=>true) %>
        <% if user_signed_in? -%>
          <%= link_to(image_tag("/images/save_as_my_list.png", :border => 0, :style=>"float:right;"), new_from_product_report_product_groups_path(:report_id => @report.id)) -%>
        <% end -%>
      <% else -%>
        <%= image_submit_tag("/images/filterout.png", :style=>"float:right;", :name=> "enable_filter", :value=>true) %>
      <% end -%>
      <%= hidden_field_tag 'form_action' %>
      <%= hidden_field_tag 'page', params[:page].blank? ? 1 : params[:page] %>

    </div>
    <% if @products.blank? -%>
      No products to show.
    <% else -%>
      <table class="prm_table" cellspacing="0">
      <tr>
        <% unless @report.filtered? -%>
          <th id="selectall"><input type='checkbox' onClick="$$('#update_product_report_form input.check').each(function(box){box.checked=checked; box.parentNode.parentNode.className = box.checked ? 'active_row' : ''});" /></th>
        <% end -%>
        <th id="prod_name" class="sortable_column"><div class="sortable_column_text"><%= link_to_remote "Product Name", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=product_name'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')"%></div>
          <% if @report.sorting_field == 5 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
        </th>
        <th id="man_name" class="sortable_column"><div class="sortable_column_text"><%= link_to_remote "Manufacturer", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=manufacturer'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')"%></div>
          <% if @report.sorting_field == 6 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
        </th>
        <th class="sortable_column" width="48px"><div class="sortable_column_text"><%= link_to_remote "CSI", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=CSI'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')"%></div>
          <% if @report.sorting_field == 1 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
          <img class="qmark" src="/images/q_mark.png" style="margin-bottom:4px" alt="" id="csi_table_header"/>
        </th>
        <th class="sortable_column" width="50px"><div class="sortable_column_text"><%= link_to_remote "PFS", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=PFS'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')" %></div>
          <% if @report.sorting_field == 2 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
          <img class="qmark" src="/images/q_mark.png" style="margin-bottom:4px" alt="" id="pfs_table_header"/>
        </th>
        <th class="sortable_column" width="51px"><div class="sortable_column_text"><%= link_to_remote "PRS", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=PRS'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')" %></div>
          <% if @report.sorting_field == 3 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
          <img class="qmark" src="/images/q_mark.png" style="margin-bottom:4px" alt="" id="prs_table_header"/>
        </th>
        <th class="sortable_column" width="50px"><div class="sortable_column_text"><%= link_to_remote "PSS", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=PSS'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')" %></div>
          <% if @report.sorting_field == 4 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
          <img class="qmark" src="/images/q_mark.png" style="margin-bottom:4px" alt="" id="pss_table_header"/>
        </th>
        <th class="report_reviews_column<%= "_sorted" if @report.sorting_field == 7 -%> sortable_column">
          <div class="sortable_column_text"><%= link_to_remote "No. of Reviews", :url  => {:controller => 'product_reports', :action => "refresh", :id => @report.id}, :with => "'sort_by=reviews_count'", :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar')" %></div>
          <% if @report.sorting_field == 7 -%>
          <div class="sortable_column_icon"><%= column_sort_icon(@report.sorting_order) %></div>
          <% end -%>
        </th>
      </tr>
      <% @products.each do |product| %>
        <tr <%= "class=\"active_row\"" if !@report.filtered? && @filtered_products.include?(product.id) -%>>
          <% unless @report.filtered? -%>
            <td><%= check_box_tag "product_ids[]", product.id,  @filtered_products.include?(product.id), :id => "product_ids_#{product.id}", :class => 'check', :onclick => "this.parentNode.parentNode.className = this.checked ? 'active_row' : ''" %></td>
          <% end -%>
          <td><%=h product.name %></td>
          <td><%=h @manufacturers[product.attributes['manufacturer']] %></td>
          <td class="scores_col"><%=h product.csi_score.to_s[0,4] %></td>
          <td class="scores_col"><%=h product.functionality_score.to_s[0,4] %></td>
          <td class="scores_col"><%=h product.reliability_score.to_s[0,4] %></td>
          <td class="scores_col"><%=h product.support_score.to_s[0,4] %></td>
          <td class="reviews_col"><%= product.reviews_count %> <%= link_to 'View Reviews', product_reviews_path(product), :target => '_blank' %></td>
        </tr>
      <% end %>
      </table>
      <div id="bottombar">
        <ul>
          <% if user_signed_in? -%>
          <li style="font-size: 1.2em; line-height: 1.8em; font-weight: bold; float:left; padding-top: 2px;">Export Options:</li>
          <li><%= link_to_remote "<img src=\"/images/page_white_acrobat.png\" alt=\"pdf\" class=\"export_icons\"/>", :url  => mail_product_report_path( :id => @report.id, :format => 'pdf'), :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar'); " -%></li>
          <li><%= link_to_remote "<img src=\"/images/page_white_excel.png\" alt=\"excel\" class=\"export_icons\"/>", :url  => mail_product_report_path( :id => @report.id, :format => 'csv'), :loading => "Element.show('loading_bar')", :complete => "Element.hide('loading_bar'); " -%></li>
					<li>
						<!-- AddThis Button BEGIN -->
						<div id="add-this-btn-prm">
							<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
								<a class="addthis_button_preferred_1"></a>
								<a class="addthis_button_preferred_2"></a>
								<a class="addthis_button_preferred_3"></a>
								<a class="addthis_button_compact"></a>
							</div>
						</div>
						<!-- AddThis Button END -->
					</li>
          <% else -%>
            <li style="font-size: 1.2em; line-height: 1.8em; font-weight: bold; float:left; padding-top: 2px;"><%= link_to 'Reports for export', new_user_registration_path -%></li>
          <% end -%>
          <% if @products.next_page -%>
            <li class="fl_right"><%= image_submit_tag("/images/nextbtnonwhite.png", :onClick => "$('update_product_report_form').form_action.value='next_page'") %></li>
          <% end -%>
          <% if @products.previous_page -%>
            <li class="fl_right"><%= image_submit_tag("/images/prv_btn_onwhite.png", :onClick => "$('update_product_report_form').form_action.value='prev_page'") %></li>
          <% end -%>
          <li class="fl_right"><label><%= page_entries_info(@products) %></label>
            <%= per_page_select(@report.items_per_page, "", "margin:2px 0;font-weight: bold;") %>
          </li>
        </ul>
      </div>
    <% end -%>
    <script type="text/javascript" charset="utf-8">
    new Tip('csi_table_header', "<b>Customer Satisfaction Index</b><br>The Customer Satisfaction Index is an aggregate measurement of the delta between a customer’s expectation of a product and their actual experience with it.", {effect: 'blind',
        hook: { tip: 'bottomLeft', target: 'topRight' },
        offset: { x: -10, y: -1 }, stem: 'bottomLeft'
    });
    new Tip('pfs_table_header', '<b>Product Functionality Score</b><br>This metric reflects the level of customer satisfaction with respect to the product meeting their expectations in terms of functionality, design and appearance.', {effect: 'blind',
        hook: { tip: 'bottomLeft', target: 'topRight' },
        offset: { x: -10, y: -1 }, stem: 'bottomLeft'
    });
    new Tip('prs_table_header', '<b>Product Reliability Score</b><br>This metric reflects the level of customer satisfaction with the product longevity and ability to perform as expected.', {effect: 'blind',
        hook: { tip: 'bottomLeft', target: 'topRight' },
        offset: { x: -10, y: -1 }, stem: 'bottomLeft'
    });
    new Tip('pss_table_header', '<b>Product Support Score</b><br>This metric reflects the level of customer satisfaction with all interactions involving the product ownership experience.', {effect: 'blind',
        hook: { tip: 'bottomLeft', target: 'topRight' },
        offset: { x: -10, y: -1 }, stem: 'bottomLeft'
    });
    </script>
  </div>
<% end -%>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<% form_for(@product) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :csi_score %><br />
    <%= f.text_field :csi_score %>
  </p>
  <p>
    <%= f.label :functionality_score %><br />
    <%= f.text_field :functionality_score %>
  </p>
  <p>
    <%= f.label :reliability_score %><br />
    <%= f.text_field :reliability_score %>
  </p>
  <p>
    <%= f.label :support_score %><br />
    <%= f.text_field :support_score %>
  </p>
  <p>
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </p>
  <p>
    <%= f.label :last_update %><br />
    <%= f.datetime_select :last_update %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/no_sufficient_data.html.erb
<div id="content_area">
<br /><br />
  <p>
    This product does not have a sufficient history.
  </p>
</div>